"""Add content column to squeak table

Revision ID: 05b0fd9110fa
Revises: 78b6e078848c
Create Date: 2021-08-24 01:36:23.256128

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '05b0fd9110fa'
down_revision = '78b6e078848c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squeak', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Binary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squeak', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
