"""Add paid column to offers tables

Revision ID: 1ba9ece09ef2
Revises: 67e84bbfd641
Create Date: 2021-02-20 17:42:12.509204

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '1ba9ece09ef2'
down_revision = '67e84bbfd641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=False))

    with op.batch_alter_table('sent_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_offer', schema=None) as batch_op:
        batch_op.drop_column('paid')

    with op.batch_alter_table('received_offer', schema=None) as batch_op:
        batch_op.drop_column('paid')

    # ### end Alembic commands ###
