"""Remove unique constrain in sent offes

Revision ID: 1e8129493870
Revises: b703368566fe
Create Date: 2021-02-16 14:36:35.724891

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '1e8129493870'
down_revision = 'b703368566fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_offer', schema=None) as batch_op:
        batch_op.drop_constraint(
            'uq_sent_offer_squeak_hash_client_addr', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_offer', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_sent_offer_squeak_hash_client_addr', [
                                          'squeak_hash', 'client_addr'])

    # ### end Alembic commands ###
