"""Use BigInteger for settle_index

Revision ID: 2e980a6e722c
Revises: 86f7ad5667c9
Create Date: 2021-02-12 01:15:46.679895

"""
import sqlalchemy as sa
from alembic import op

from squeaknode.db.models import SLBigInteger


# revision identifiers, used by Alembic.
revision = '2e980a6e722c'
down_revision = '86f7ad5667c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('received_payment', 'settle_index',
                    existing_type=sa.Integer(), type_=SLBigInteger())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('received_payment', 'settle_index',
                    existing_type=SLBigInteger(), type_=sa.Integer())
    # ### end Alembic commands ###
