"""Add profile image column to profile table

Revision ID: 6851569c46e3
Revises: d5a06570ed3e
Create Date: 2021-01-28 23:25:31.015184

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '6851569c46e3'
down_revision = 'd5a06570ed3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('profile_image', sa.Binary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
