"""Remove peer uploading and downloading fields, add autoconnect field

Revision ID: 7868889c72e3
Revises: 7f9632136152
Create Date: 2021-08-20 14:20:38.979040

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '7868889c72e3'
down_revision = '7f9632136152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peer', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('autoconnect', sa.Boolean(), nullable=False))
        batch_op.drop_column('downloading')
        batch_op.drop_column('uploading')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peer', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('uploading', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(
            sa.Column('downloading', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('autoconnect')

    # ### end Alembic commands ###
