"""Use peer hash for peer primary key

Revision ID: 9eb4ba6da999
Revises: d1cf733279c4
Create Date: 2021-02-02 22:14:57.682676

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.sql import column
from sqlalchemy.sql import table

from squeaknode.core.util import get_peer_hash


# revision identifiers, used by Alembic.
revision = '9eb4ba6da999'
down_revision = 'd1cf733279c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the peer_hash column
    with op.batch_alter_table('peer', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('peer_hash', sa.String(length=64), nullable=False))
    with op.batch_alter_table('received_offer', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('peer_hash', sa.String(length=64), nullable=False))
    with op.batch_alter_table('sent_payment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('peer_hash', sa.String(length=64), nullable=False))

    peers = table(
        "peer",
        column("peer_hash", String(64)),
        column("server_host", String),
        column("server_port", Integer),
    )

    # Set the peer_hash column in the peers table.
    op.execute(
        peers.update().
        values(
            peer_hash=get_peer_hash(
                peers.c.server_host,
                peers.c.server_port,
            ).hex(),
        )
    )

    # Delete peer_id and create the primary key on peer_hash
    with op.batch_alter_table('peer', schema=None) as batch_op:
        batch_op.drop_column('peer_id')
        batch_op.create_primary_key(
            "pk_peer", ["peer_hash"]
        )
    with op.batch_alter_table('received_offer', schema=None) as batch_op:
        batch_op.drop_column('peer_id')
    with op.batch_alter_table('sent_payment', schema=None) as batch_op:
        batch_op.drop_column('peer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peer', schema=None) as batch_op:
        batch_op.drop_constraint("pk_peer")
        batch_op.add_column(sa.Column('peer_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('peer_hash')
    with op.batch_alter_table('received_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peer_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('peer_hash')
    with op.batch_alter_table('sent_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peer_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('peer_hash')

    # ### end Alembic commands ###
