"""Make reply to hash nullable

Revision ID: adec68bd0785
Revises: a35d180bf020
Create Date: 2021-08-24 17:10:21.009027

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'adec68bd0785'
down_revision = 'a35d180bf020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squeak', schema=None) as batch_op:
        batch_op.alter_column('hash_reply_sqk',
                              existing_type=sa.VARCHAR(length=64),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squeak', schema=None) as batch_op:
        batch_op.alter_column('hash_reply_sqk',
                              existing_type=sa.VARCHAR(length=64),
                              nullable=False)

    # ### end Alembic commands ###
