"""Add content column to squeak table

Revision ID: c0316d4931a5
Revises: 78b6e078848c
Create Date: 2021-08-24 02:06:47.850900

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'c0316d4931a5'
down_revision = '78b6e078848c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squeak', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('content', sa.String(length=280), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squeak', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
