"""Use address for profile primary key

Revision ID: d1cf733279c4
Revises: 6851569c46e3
Create Date: 2021-02-02 17:12:40.262077

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd1cf733279c4'
down_revision = '6851569c46e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('profile_id')
        batch_op.create_primary_key(
            "pk_profile", ["address"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint("pk_profile")
        batch_op.add_column(
            sa.Column('profile_id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
