"""Add composite unique constraint on squeak hash and client addr of sent offer

Revision ID: d5a06570ed3e
Revises: cd3f18ee33c8
Create Date: 2021-01-28 17:49:17.615748

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd5a06570ed3e'
down_revision = 'cd3f18ee33c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_offer', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_sent_offer_squeak_hash_client_addr', [
                                          'squeak_hash', 'client_addr'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_offer', schema=None) as batch_op:
        batch_op.drop_constraint(
            'uq_sent_offer_squeak_hash_client_addr', type_='unique')

    # ### end Alembic commands ###
