"""Add valid column to sent_payment table

Revision ID: df59995f322c
Revises: afb1f38de2cb
Create Date: 2021-01-21 18:18:22.589806

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql.expression import literal


# revision identifiers, used by Alembic.
revision = 'df59995f322c'
down_revision = 'afb1f38de2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid', sa.Boolean(),
                                      server_default=literal(True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_payment', schema=None) as batch_op:
        batch_op.drop_column('valid')

    # ### end Alembic commands ###
