CREATE DATABASE squeakserver;

\connect squeakserver;

CREATE SCHEMA IF NOT EXISTS mainnet;
CREATE SCHEMA IF NOT EXISTS testnet;
CREATE SCHEMA IF NOT EXISTS regtest;
CREATE SCHEMA IF NOT EXISTS simnet;
