"""Use price_msat in sent_payment table

Revision ID: 434b1c53bc45
Revises: e771283d1959
Create Date: 2020-11-10 02:14:57.999127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434b1c53bc45'
down_revision = 'e771283d1959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_msat', sa.Integer(), nullable=False, server_default=sa.text("0")))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), nullable=False, server_default=sa.text("0")))
        batch_op.drop_column('price_msat')

    # ### end Alembic commands ###
