"""Add client_addr to sent offer table

Revision ID: 59c8e45671e1
Revises: f8ca6a6fa220
Create Date: 2020-11-13 04:08:24.956685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c8e45671e1'
down_revision = 'f8ca6a6fa220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_addr', sa.String(length=64), nullable=False, server_default=''))

    with op.batch_alter_table('sent_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_addr', sa.String(length=64), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_offer', schema=None) as batch_op:
        batch_op.drop_column('client_addr')

    with op.batch_alter_table('received_payment', schema=None) as batch_op:
        batch_op.drop_column('client_addr')

    # ### end Alembic commands ###
