"""Initialize all

Revision ID: e771283d1959
Revises: 
Create Date: 2020-11-08 19:23:46.430021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e771283d1959'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('squeak_hash', sa.String(length=64), nullable=False),
    sa.Column('key_cipher', sa.Binary(), nullable=False),
    sa.Column('iv', sa.Binary(), nullable=False),
    sa.Column('payment_hash', sa.String(length=64), nullable=False),
    sa.Column('invoice_timestamp', sa.Integer(), nullable=False),
    sa.Column('invoice_expiry', sa.Integer(), nullable=False),
    sa.Column('price_msat', sa.Integer(), nullable=False),
    sa.Column('payment_request', sa.String(), nullable=False),
    sa.Column('destination', sa.String(length=66), nullable=False),
    sa.Column('node_host', sa.String(), nullable=False),
    sa.Column('node_port', sa.Integer(), nullable=False),
    sa.Column('peer_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_table('peer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('peer_name', sa.String(), nullable=True),
    sa.Column('server_host', sa.String(), nullable=False),
    sa.Column('server_port', sa.Integer(), nullable=False),
    sa.Column('uploading', sa.Boolean(), nullable=False),
    sa.Column('downloading', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('private_key', sa.Binary(), nullable=True),
    sa.Column('address', sa.String(length=35), nullable=False),
    sa.Column('sharing', sa.Boolean(), nullable=False),
    sa.Column('following', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('profile_name')
    )
    op.create_table('sent_payment',
    sa.Column('sent_payment_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('peer_id', sa.Integer(), nullable=False),
    sa.Column('squeak_hash', sa.String(length=64), nullable=False),
    sa.Column('preimage_hash', sa.String(length=64), nullable=False),
    sa.Column('preimage', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('node_pubkey', sa.String(length=66), nullable=False),
    sa.Column('preimage_is_valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('sent_payment_id')
    )
    op.create_table('squeak',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('n_version', sa.Integer(), nullable=False),
    sa.Column('hash_enc_content', sa.String(length=64), nullable=False),
    sa.Column('hash_reply_sqk', sa.String(length=64), nullable=False),
    sa.Column('hash_block', sa.String(length=64), nullable=False),
    sa.Column('n_block_height', sa.Integer(), nullable=False),
    sa.Column('vch_script_pub_key', sa.Binary(), nullable=False),
    sa.Column('vch_encryption_key', sa.Binary(), nullable=False),
    sa.Column('enc_data_key', sa.String(), nullable=False),
    sa.Column('iv', sa.String(length=64), nullable=False),
    sa.Column('n_time', sa.Integer(), nullable=False),
    sa.Column('n_nonce', sa.BigInteger(), nullable=False),
    sa.Column('enc_content', sa.String(length=2272), nullable=False),
    sa.Column('vch_script_sig', sa.Binary(), nullable=False),
    sa.Column('author_address', sa.String(length=35), nullable=False),
    sa.Column('vch_decryption_key', sa.Binary(), nullable=True),
    sa.Column('block_header', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_squeak_author_address'), 'squeak', ['author_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_squeak_author_address'), table_name='squeak')
    op.drop_table('squeak')
    op.drop_table('sent_payment')
    op.drop_table('profile')
    op.drop_table('peer')
    op.drop_table('offer')
    # ### end Alembic commands ###
