version: '3'
services:

  bitcoin-core:
    command:
      -printtoconsole
      -testnet=1
      -server=1
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -rpcuser=devuser
      -rpcpassword=devpass
      -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333

  lnd:
    environment:
      - NETWORK=testnet

  eclair:
    environment:
      - NETWORK=testnet

  squeaknode:
    environment:
      - NETWORK=testnet

volumes:
  # shared volume is needed for sharing the btcd certificate
  shared:
    driver: local
