version: '3'
services:

  btcd:
    image: btcd
    container_name: btcd
    build:
      context: ../
      dockerfile: docker/btcd/Dockerfile
    volumes:
      - shared_test:/rpc
      - bitcoin_test:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - DEBUG
      - MINING_ADDRESS
    ports:
      - 8334:8334
      - 18334:18334
      - 18556:18556
      - 28902:28902
    entrypoint: ["./start-btcd.sh"]

  btcctl:
    image: btcd
    container_name: btcctl
    build:
      context: ../
      dockerfile: docker/btcd/Dockerfile
    volumes:
      - shared_test:/rpc
      - bitcoin_test:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - DEBUG
      - MINING_ADDRESS
    links:
      - "btcd:rpcserver"
    entrypoint: ["./start-btcctl.sh"]

  lnd_alice:
    image: lnd
    container_name: lnd_alice
    build:
      context: ../
      dockerfile: docker/lnd/Dockerfile
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
    volumes:
      - shared_test:/rpc
      - lnd_dir_alice:/root/.lnd
    links:
      - "btcd:blockchain"
    entrypoint: ["./start-lnd.sh"]

  lnd_sqkserver:
    image: lnd
    container_name: lnd_sqkserver
    build:
      context: ../
      dockerfile: docker/lnd/Dockerfile
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
    volumes:
      - shared_test:/rpc
      - lnd_dir_sqkserver:/root/.lnd
    links:
      - "btcd:blockchain"
    entrypoint: ["./start-lnd.sh"]

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./createdb.sql:/docker-entrypoint-initdb.d/init.sql

  sqkserver:
    image: sqkserver
    container_name: sqkserver
    build:
      context: ../
      dockerfile: docker/sqkserver/Dockerfile
    volumes:
      - shared_test:/rpc
      - lnd_dir_sqkserver:/root/.lnd
      - ./config.ini:/app/config.ini
    links:
      - "lnd_sqkserver:lnd"
    depends_on:
      - db
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  test:
    image: test
    container_name: test
    build:
      context: ../
      dockerfile: docker/test/Dockerfile
    volumes:
      - shared_test:/rpc
      - lnd_dir_alice:/root/.lnd
    links:
      - "lnd_alice:lnd"
    command: tail -f /dev/null

volumes:
  # btcctl and lnd containers.
  shared_test:
    driver: local

  # bitcoin_test volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin_test:
    driver: local

  # lnd_dir volume is needed for sharing tht tls certificate
  lnd_dir_alice:
    driver: local
  lnd_dir_sqkserver:
    driver: local
