version: '3'
services:

  btcd:
    image: btcd
    container_name: test_btcd
    build:
      context: ../
      dockerfile: docker/btcd/Dockerfile
    volumes:
      - test_shared:/rpc
      - test_bitcoin:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - DEBUG
      - MINING_ADDRESS
    ports:
      - 8334:8334
      - 18334:18334
      - 18556:18556
      - 28902:28902
    entrypoint: ["./start-btcd.sh"]

  btcctl:
    image: btcd
    container_name: test_btcctl
    build:
      context: ../
      dockerfile: docker/btcd/Dockerfile
    volumes:
      - test_shared:/rpc
      - test_bitcoin:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - DEBUG
      - MINING_ADDRESS
    links:
      - "btcd:rpcserver"
    entrypoint: ["./start-btcctl.sh"]

  lnd_client:
    image: lnd
    container_name: test_lnd_client
    build:
      context: ../
      dockerfile: docker/lnd/Dockerfile
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
    volumes:
      - test_shared:/rpc
      - test_lnd_client_dir:/root/.lnd
    links:
      - "btcd:blockchain"
    entrypoint: ["./start-lnd.sh"]

  lnd_server:
    image: lnd
    container_name: test_lnd_server
    build:
      context: ../
      dockerfile: docker/lnd/Dockerfile
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
    volumes:
      - test_shared:/rpc
      - test_lnd_server_dir:/root/.lnd
    links:
      - "btcd:blockchain"
    entrypoint: ["./start-lnd.sh"]

  db:
    image: postgres
    container_name: test_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../createdb.sql:/docker-entrypoint-initdb.d/init.sql

  sqkserver:
    image: sqkserver
    container_name: test_sqkserver
    build:
      context: ../
      dockerfile: docker/sqkserver/Dockerfile
    volumes:
      - test_shared:/rpc
      - test_lnd_server_dir:/root/.lnd
      - ./config.ini:/app/config.ini
    links:
      - "btcd:btcd"
      - "lnd_server:lnd"
    depends_on:
      - db
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    entrypoint: ["./start-sqkserver.sh"]

  test:
    image: test
    container_name: test
    build:
      context: ../
      dockerfile: docker/test/Dockerfile
    volumes:
      - test_shared:/rpc
      - test_lnd_client_dir:/root/.lnd
    links:
      - "lnd_client:lnd"
    command: tail -f /dev/null

volumes:
  # btcctl and lnd containers.
  test_shared:
    driver: local

  # test_bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  test_bitcoin:
    driver: local

  # lnd_dir volume is needed for sharing tht tls certificate
  test_lnd_client_dir:
    driver: local
  test_lnd_server_dir:
    driver: local
